### ISSUE TITLE
Does the preconfigurator have logging, so that I can see where it fails/succeeds?

### ISSUE THREAD

**Issue by paul-mcgrath** [RamjotSingh/PreConfiguratorForTraefikOnServiceFabric#6]
Just having some difficulty with visibility on this .exe, as it runs in Service Fabric but I have no idea what's wrong if it fails to configure correctly.

**Comment by RamjotSingh** [comment]
It uses ApplicationInsights. You can set the key and the logs will be sent to AppInsights.

**Comment by paul-mcgrath** [comment]
Thanks Ramjot, I had registered the key, but it still isn't sending events for some reason.

**Comment by jan-chvojka** [comment]
I could not get AI working too. I had to add call telemetryClient.Flush(); before program exited.

**Comment by RamjotSingh** [comment]
@jan-chvojka Adding fix for this in https://github.com/RamjotSingh/PreConfiguratorForTraefikOnServiceFabric/pull/9
