### ISSUE TITLE
Instructions for associating an Application with KeyVault point to examples for Azure web apps

### ISSUE THREAD

**Issue by paul-mcgrath** [RamjotSingh/PreConfiguratorForTraefikOnServiceFabric#7]
Are there any instructions on how to associate an Application with KeyVault in Service Fabric?

I'm getting stuck at this step, as I'm not sure how to allow the preconfigurator to pull certs
from KeyVault from within a Service Fabric cluster, and the linked instructions are for Azure Web Apps.

Thank you!

**Comment by RamjotSingh** [comment]
The instructions for Service Fabric aren't any different (infact the current ones are for Service Fabric). Just follow the ReadMe.md on how to setup. Let me know where you are hitting issues and I can help.

**Comment by paul-mcgrath** [comment]
Hi Ramjot,

Thank you for offering your help, which is very kind.

The instructions list the following step:
- **TraefikKeyVaultClientId** - Only required if using KeyVault. An Application must be associated with KeyVault to access it. Refer  this (https://docs.microsoft.com/en-us/azure/key-vault/key-vault-use-from-web-application#authenticate-with-a-certificate-instead-of-a-client-secret) to setup.

I don't see an "authenticate-with-a-certificate-instead-of-a-client-secret" section in that article anymore, and it seems to just focus on Azure Web Apps. 

The difficulty I am having (perhaps because I am relatively new to this part of the Azure portal) is that I am unsure how to link a Service Fabric Application with KeyVault.

Any advice would be great!

**Comment by RamjotSingh** [comment]
Those instructions are pretty much still valid. However I realize they have changed the page a lot and built it more catered to Web Apps now. Here are the instructions let me know if these work out for you.

1. Go to Azure Portal > Azure Active Directory > App Registrations > Register a new Web Api App
2. Once the app is created > Open App > Settings > Keys > Upload the public part of the cert (Copy the thumbprint and AAD Application Id)
3. Go to KeyVault > Access Policies > Select Principal > Search and select the AAD Application > Give Certification and Secret Get and List Permissions at least
4. Add the details to Traefik configuration TraefikKeyVaultClientId is the AAD Application Id above and KeyVaultClientCert is the certificate thumbprint from step 2. Remember the must be installed on the cluster machines in LocalMachine\My store

Let me know if these instructions help.

**Comment by paul-mcgrath** [comment]
This is incredibly useful, thank you!

One clarification on this: for point 2, you said "upload the public part of the cert".
Is this cert generated as part of the app registration process?

**Comment by RamjotSingh** [comment]
No the cert needs to be provided by you. It can be a self signed cert too. You can alternatively also use ClientSecret, however that requires you to put the secret in your config which is not recommended for security reasons.

**Comment by paul-mcgrath** [comment]
Thank you, Ramjot. I'll close this issue now, as this has been very helpful!
